### ISSUE TITLE
About the data

### ISSUE THREAD

**Issue by OleNet** [hadyelsahar/CNN-RelationExtraction#1]
Hi hadyelsahar, I have clone your code, and try to run the rel-graphrelations_example.py. However, I find that this program lacks .txt data and the corresponding .ann data. I assume those file are from [brat](http://brat.nlplab.org),  but I don't know which data you have used to write those code, so can you share the data or the link, please?

**Comment by hadyelsahar** [comment]
@OleNet  : thanks for the insterest !! in fact this code is still unpublished and under development. Both the dataset and the relations annotation is still being made at the moment. 
I'll keep you updated once i finish it.

**Comment by OleNet** [comment]
OK, I got it. Thanks for the reply!
